import React from "react";

// reactstrap components
import {
  Card,
  CardHeader,
  CardBody,
  Collapse,
} from "reactstrap";

function Collapses() {
  // collapse states and functions
  const [collapses, setCollapses] = React.useState([]);
  const changeCollapse = collapse => {
    if (collapses.includes(collapse)) {
      setCollapses(collapses.filter(prop => prop !== collapse));
    } else {
      setCollapses([...collapses, collapse]);
    }
  };
  return (
    <>
      <div id="acordeon">
        <div aria-multiselectable={true} id="accordion" role="tablist">
          <Card className="no-transition" style={{background:"#0b0e27"}}>
            <CardHeader className="card-collapse" id="headingOne" role="tab">
              <h5 className="mb-3 panel-title" style={{background:"white"}}>
                <a
                  aria-expanded={collapses.includes(1)}
                  className="collapsed"
                  data-parent="#accordion"
                  href="#pablo"
                  id="collapseOne"
                  onClick={e => {
                    e.preventDefault();
                    changeCollapse(1);
                  }}
                >
                  
                  What is Rapixo about? 
                                    {" "} <span style={{float:"right"}}>+</span>
                  <i className="nc-icon nc-minimal-down" />
                </a>
              </h5>
            </CardHeader>
            <Collapse isOpen={collapses.includes(1)}>
              <CardBody>
              Rapixo is a utility based project focused on music in the Web 3.0 space, our holders will benefit through the streaming revenue which will be generated by artists allowing you to invest into music for the first time ever. Our 3D tech is ready to use! All of our 3D Volumetric Scanning Technology is fully functional and is currently located in Shanghai, China. Post-Mint an LA studio will be setup to better access the targeted demographic of artists. We're focused around providing as much uitility to our holders as possible. 
              <br></br>
                <br></br>

              </CardBody>
            </Collapse>
            <CardHeader className="card-collapse" id="headingTwo" role="tab">
              <h5 className="mb-3 panel-title" style={{background:"white"}}>
                <a
                  aria-controls="collapseTwo"
                  aria-expanded={collapses.includes(2)}
                  className="collapsed"
                  data-parent="#accordion"
                  href="#pablo"
                  id="collapseTwo"
                  onClick={e => {
                    e.preventDefault();
                    changeCollapse(2);
                  }}
                >
                  
                  What are the utilities that come with holding a Rapixo NFT?
 
 {" "} <span style={{float:"right"}}>+</span>
                  <i className="nc-icon nc-minimal-down" />
                </a>
              </h5>
            </CardHeader>
            <Collapse isOpen={collapses.includes(2)}>
              <CardBody>
              Here are some of utilities that come with holding a Rapixo NFT! <br></br>
 - Free mint for Rapixo Gen 2.<br></br>
- Free customizable NFT display with their favorite spotify code, NFT OS QR code and Wallet Name.<br></br>
-  ETH airdrops from streaming sales and Music NFT sales through our Record Label <br></br>
-  Tons of WL spots from top-tier NFT projects and professional Alpha from industry leading experts.<br></br>
-  Exclusive and free access to all real life and metaverse Rapixo events.<br></br>
-  Voting rights in Rapixo DAO<br></br>
- All Gen 1 Rapixo NFTs will be 1/1 <br></br>
- Further utilities will be announced at a later date, as we'll maximize utility and value for our Gen 1 Holders.


              <br></br>
                <br></br>
              </CardBody>
            </Collapse>
            <CardHeader
              className="card-collapse"
              id="headingThree"
              role="tab"
            >
              <h5 className="mb-3 panel-title" style={{background:"white"}}>
                <a
                  aria-controls="collapseThree"
                  aria-expanded={collapses.includes(3)}
                  className="collapsed"
                  data-parent="#accordion"
                  href="#pablo"
                  id="collapseThree"
                  onClick={e => {
                    e.preventDefault();
                    changeCollapse(3);
                  }}
                >
                 
                 What about Mint Information? 
                                    {" "} <span style={{float:"right"}}>+</span>
                  <i className="nc-icon nc-minimal-down" />
                </a>
              </h5>
            </CardHeader>
            <Collapse isOpen={collapses.includes(3)}>
              <CardBody>
              We will have our mint on "time displayed in users timezone"
Hit-Listed members can mint 2 NFTs <br></br>
OG members can mint 3 NFTs <br></br>
In case you're unable to mint your WL spot will be carried over to Rapixo Gen 2, no whitelist spots will be wasted. 
              <br></br>
                <br></br>

              </CardBody>
            </Collapse>
            <CardHeader
              className="card-collapse"
              id="headingThree"
              role="tab"
            >
              <h5 className="mb-3 panel-title" style={{background:"white"}}>
              <a
                  aria-controls="collapseThree"
                  aria-expanded={collapses.includes(3)}
                  className="collapsed"
                  data-parent="#accordion"
                  href="#pablo"
                  id="collapseThree"
                  onClick={e => {
                    e.preventDefault();
                    changeCollapse(4);
                  }}
                >
                 

                 What is Rapixo Gen 1 and Rapixo Gen 2?
                                                                        {" "} <span style={{float:"right"}}>+</span>
                  <i className="nc-icon nc-minimal-down" />
                </a>
              </h5>
            </CardHeader>
            <Collapse isOpen={collapses.includes(4)}>
              <CardBody >
              Initially we were going to mint with a supply of 5,555 NFTs, however due to the bearish market conditions and the unforseen setback of our twitter suspension we decided to release a supply of 777 NFTs only, we doubled down on the utilities for our Gen 1 holders to make sure we can prove our ability to provide Web 3.0 leading utility to our holders. We will always stand by our early supporters and make sure that we provide maximum utility and value to them. <br></br>

Gen 2 collection will have 4778 pieces only, and whitelist holders who're unable to mint the Gen 1 collection will carry over their spot to Gen 2, we will keep on building and more details on the Gen 2 collection will be released shortly after.

              <br></br>
                <br></br>

              </CardBody>
            </Collapse>
           
              
                 

                
               
          </Card>
        </div>
        {/* end acordeon */}
      </div>
    </>
  );
}

export default Collapses;